# Pandas — Data Analysis with Python

A practical, structured notebook for learning Pandas from the basics to real data-cleaning and analysis workflows.

### What this notebook covers
1. What Pandas is and why it is useful
2. Series and DataFrames
3. Creating and loading data
4. Exploring and inspecting data
5. Accessing rows and columns
6. Sorting and indexing
7. Filtering data
8. Transforming columns
9. Handling missing values and duplicates
10. Data types and string operations
11. Outlier detection
12. GroupBy and aggregation
13. Merging and concatenating DataFrames

> The examples are self-contained, so the notebook can be run without external CSV files.

## 1. Introduction

Pandas is an open-source Python library used for **data manipulation, cleaning, exploration, and analysis**.

It is built around two core structures:

- **Series** — a one-dimensional labeled array
- **DataFrame** — a two-dimensional labeled table

Pandas is commonly used before machine-learning work for tasks such as data cleaning, exploratory analysis, feature preparation, and exporting processed data.

In [1]:
import pandas as pd

print(f"Pandas version: {pd.__version__}")

Pandas version: 2.2.3

## 2. Series

A **Series** is a one-dimensional labeled array.

You can think of it as:

- one column of a table
- a Python sequence with labels
- a structure where every value has an associated index

The default index is `0, 1, 2, ...`, but custom labels can also be used.

In [2]:
scores = pd.Series([234, 542, 345, 685])
scores

0    234
1    542
2    345
3    685
dtype: int64

### Custom indexes

The index does not have to be numeric. Meaningful labels can make data easier to access.

In [3]:
scores = pd.Series(
    [234, 542, 345, 685],
    index=["student 1", "student 2", "student 3", "student 4"]
)

scores

student 1    234
student 2    542
student 3    345
student 4    685
dtype: int64

In [4]:
# Label-based access
print("student 1:", scores.loc["student 1"])

# Position-based access
print("third value:", scores.iloc[2])

student 1: 234
third value: 345

### Updating Series values

- `.loc[]` accesses data by **label**
- `.iloc[]` accesses data by **position**

In [5]:
scores.loc["student 2"] = 500
scores.iloc[2] = 400
scores.iloc[0] += 55

scores

student 1    289
student 2    500
student 3    400
student 4    685
dtype: int64

### Filtering a Series

Boolean filtering works in a vectorized way, similar to NumPy.

In [6]:
scores[scores >= 400]

student 2    500
student 3    400
student 4    685
dtype: int64

### Creating a Series from a dictionary

Dictionary keys become the Series index.

In [7]:
student_scores = {
    "student 1": 234,
    "student 2": 542,
    "student 3": 345,
    "student 4": 685
}

scores_from_dict = pd.Series(student_scores)
scores_from_dict

student 1    234
student 2    542
student 3    345
student 4    685
dtype: int64

## 3. DataFrames

A **DataFrame** is a two-dimensional table with labeled rows and columns.

It is the main Pandas structure you will use for tabular data.

A useful mental model:

- rows → observations
- columns → variables/features
- index → row labels

A DataFrame column is itself a **Series**.

In [8]:
students = pd.DataFrame({
    "Name": ["Marwan", "Ali", "Mahmoud", "Hager"],
    "Subteam": ["AI", "Navigation", "Hardware", "Navigation"],
    "Join_Date": [2025, 2025, 2024, 2025],
    "Score": [92, 85, 78, 95]
})

students

      Name     Subteam  Join_Date  Score
0   Marwan          AI       2025     92
1      Ali  Navigation       2025     85
2  Mahmoud    Hardware       2024     78
3    Hager  Navigation       2025     95

### Creating DataFrames in different ways

A DataFrame can be created from a dictionary, a list of lists, or with a custom index.

In [9]:
# From a list of lists
df_list = pd.DataFrame(
    [[1, 2], [3, 4]],
    columns=["A", "B"]
)

df_list

   A  B
0  1  2
1  3  4

In [10]:
# With a custom index
df_custom = pd.DataFrame(
    [[1, 2], [3, 4]],
    columns=["A", "B"],
    index=["row_1", "row_2"]
)

df_custom

       A  B
row_1  1  2
row_2  3  4

## 4. Loading and Saving Data

Pandas supports many common data formats.

```python
pd.read_csv("data.csv")
pd.read_excel("data.xlsx")
pd.read_json("data.json")
pd.read_sql(query, connection)
pd.read_parquet("data.parquet")
```

Useful `read_csv()` parameters include:

- `sep` — change the delimiter
- `usecols` — load selected columns
- `nrows` — load only the first N rows
- `index_col` — use a column as the index
- `parse_dates` — parse date columns
- `na_values` — specify additional missing-value markers

For exporting:

```python
df.to_csv("output.csv", index=False)
```

### A self-contained `read_csv()` example

Using `StringIO` lets us demonstrate CSV loading without depending on a file that exists on your computer.

In [ ]:


csv_data = 

loaded_df = pd.read_csv(csv_data)
loaded_df

      Name     Subteam  Join_Date  Score
0   Marwan          AI       2025     92
1      Ali  Navigation       2025     85
2  Mahmoud    Hardware       2024     78
3    Hager  Navigation       2025     95

## 5. Exploring Your Data

After loading a dataset, the first step should be **inspection**.

Important commands:

- `head()` → first rows
- `tail()` → last rows
- `sample()` → random rows
- `info()` → structure, data types, and missing values
- `describe()` → numerical summary statistics
- `shape` → number of rows and columns
- `dtypes` → data type of every column
- `nunique()` → number of unique values
- `unique()` → actual unique values

In [12]:
print("Shape:", students.shape)
print("\nColumns:", students.columns.tolist())
print("\nData types:")
print(students.dtypes)

Shape: (4, 4)

Columns: ['Name', 'Subteam', 'Join_Date', 'Score']

Data types:
Name         object
Subteam      object
Join_Date     int64
Score         int64
dtype: object

In [13]:
students.head(2)

     Name     Subteam  Join_Date  Score
0  Marwan          AI       2025     92
1     Ali  Navigation       2025     85

In [14]:
students.tail(2)

      Name     Subteam  Join_Date  Score
2  Mahmoud    Hardware       2024     78
3    Hager  Navigation       2025     95

In [15]:
students.sample(2, random_state=42)

    Name     Subteam  Join_Date  Score
1    Ali  Navigation       2025     85
3  Hager  Navigation       2025     95

In [16]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      object
 1   Subteam    4 non-null      object
 2   Join_Date  4 non-null      int64
 3   Score      4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [17]:
students.describe()

       Join_Date      Score
count       4.00   4.000000
mean     2024.75  87.500000
std         0.50   7.593857
min      2024.00  78.000000
25%      2024.75  83.250000
50%      2025.00  88.500000
75%      2025.00  92.750000
max      2025.00  95.000000

In [18]:
print("Unique Subteams:")
print(students["Subteam"].unique())

print("\nNumber of unique values:")
print(students.nunique())

Unique Subteams:
['AI' 'Navigation' 'Hardware']

Number of unique values:
Name         4
Subteam      3
Join_Date    2
Score        4
dtype: int64

## 6. Accessing Columns and Rows

### Column access

A single column returns a Series:

```python
df["Score"]
```

Multiple columns return a DataFrame:

```python
df[["Name", "Score"]]
```

Dot notation such as `df.Score` is possible when the column name is a valid Python attribute, but bracket notation is generally safer and more consistent.

In [19]:
students["Score"]

0    92
1    85
2    78
3    95
Name: Score, dtype: int64

In [20]:
students[["Name", "Subteam", "Score"]]

      Name     Subteam  Score
0   Marwan          AI     92
1      Ali  Navigation     85
2  Mahmoud    Hardware     78
3    Hager  Navigation     95

### `loc` vs `iloc`

**`loc`** is label-based.

```python
df.loc[row_label, column_label]
```

**`iloc`** is position-based.

```python
df.iloc[row_position, column_position]
```

A key difference is slicing:

- `loc` includes the ending label
- `iloc` excludes the ending position

In [21]:
students.loc[0, "Score"]

np.int64(92)

In [22]:
students.iloc[0, 2]

np.int64(2025)

In [23]:
students.loc[0:2, ["Name", "Score"]]

      Name  Score
0   Marwan     92
1      Ali     85
2  Mahmoud     78

In [24]:
students.iloc[0:3, 0:2]

      Name     Subteam
0   Marwan          AI
1      Ali  Navigation
2  Mahmoud    Hardware

### `at` and `iat`

When you need one specific cell:

- `.at[]` → label-based scalar access
- `.iat[]` → position-based scalar access

In [25]:
print("at:", students.at[0, "Name"])
print("iat:", students.iat[0, 0])

at: Marwan
iat: Marwan

## 7. Sorting and Indexing

Use `sort_values()` to sort by one or more columns.

In [26]:
sorted_students = students.sort_values("Score")
sorted_students

      Name     Subteam  Join_Date  Score
2  Mahmoud    Hardware       2024     78
1      Ali  Navigation       2025     85
0   Marwan          AI       2025     92
3    Hager  Navigation       2025     95

In [27]:
students.sort_values("Score", ascending=False)

      Name     Subteam  Join_Date  Score
3    Hager  Navigation       2025     95
0   Marwan          AI       2025     92
1      Ali  Navigation       2025     85
2  Mahmoud    Hardware       2024     78

In [28]:
students.sort_values(
    ["Subteam", "Score"],
    ascending=[True, False]
)

      Name     Subteam  Join_Date  Score
0   Marwan          AI       2025     92
2  Mahmoud    Hardware       2024     78
3    Hager  Navigation       2025     95
1      Ali  Navigation       2025     85

You can also sort by the index:

```python
df.sort_index()
```

After filtering or sorting, you may want a clean sequential index:

```python
df.reset_index(drop=True)
```

In [29]:
filtered_index = students[students["Score"] >= 85]
filtered_index.reset_index(drop=True)

     Name     Subteam  Join_Date  Score
0  Marwan          AI       2025     92
1     Ali  Navigation       2025     85
2   Hager  Navigation       2025     95

## 8. Filtering Data

Boolean indexing returns rows where a condition is `True`.

Use:

- `&` for AND
- `|` for OR
- `~` for NOT

Put each condition inside parentheses.

In [30]:
# Single condition
students[students["Score"] > 85]

     Name     Subteam  Join_Date  Score
0  Marwan          AI       2025     92
3   Hager  Navigation       2025     95

In [31]:
# AND
students[
    (students["Score"] > 80) &
    (students["Join_Date"] >= 2025)
]

     Name     Subteam  Join_Date  Score
0  Marwan          AI       2025     92
1     Ali  Navigation       2025     85
3   Hager  Navigation       2025     95

In [32]:
# OR
students[
    (students["Subteam"] == "AI") |
    (students["Subteam"] == "Hardware")
]

      Name   Subteam  Join_Date  Score
0   Marwan        AI       2025     92
2  Mahmoud  Hardware       2024     78

In [33]:
# NOT
students[~(students["Subteam"] == "Navigation")]

      Name   Subteam  Join_Date  Score
0   Marwan        AI       2025     92
2  Mahmoud  Hardware       2024     78

### `isin()`

Useful when a column should match one of several possible values.

In [34]:
students[students["Subteam"].isin(["AI", "Navigation"])]

     Name     Subteam  Join_Date  Score
0  Marwan          AI       2025     92
1     Ali  Navigation       2025     85
3   Hager  Navigation       2025     95

### `between()`

`between()` checks whether values are inside an inclusive range.

In [35]:
students[students["Score"].between(80, 95)]

     Name     Subteam  Join_Date  Score
0  Marwan          AI       2025     92
1     Ali  Navigation       2025     85
3   Hager  Navigation       2025     95

### `query()`

`query()` provides a SQL-like way to write filters.

In [36]:
students.query("Score > 85 and Join_Date >= 2025")

     Name     Subteam  Join_Date  Score
0  Marwan          AI       2025     92
3   Hager  Navigation       2025     95

### `where()` and `mask()`

These are useful for conditional replacement.

- `where(condition)` keeps values where the condition is `True`
- `mask(condition)` replaces values where the condition is `True`

They are opposites.

In [37]:
scores_demo = students["Score"].copy()

print("where():")
print(scores_demo.where(scores_demo >= 85))

print("\nmask():")
print(scores_demo.mask(scores_demo < 85, other=0))

where():
0    92.0
1    85.0
2     NaN
3    95.0
Name: Score, dtype: float64

mask():
0    92
1    85
2     0
3    95
Name: Score, dtype: int64

## 9. Adding, Removing, and Transforming Columns

A column can be added directly.

You can create a column from:

- a constant
- another column
- a calculation involving several columns

In [38]:
students_enhanced = students.copy()

students_enhanced["Passed"] = students_enhanced["Score"] >= 60
students_enhanced["Score_Percent"] = students_enhanced["Score"] / 100

students_enhanced

      Name     Subteam  Join_Date  Score  Passed  Score_Percent
0   Marwan          AI       2025     92    True           0.92
1      Ali  Navigation       2025     85    True           0.85
2  Mahmoud    Hardware       2024     78    True           0.78
3    Hager  Navigation       2025     95    True           0.95

### `apply()`

`apply()` can apply a function to each value in a Series.

It is useful for readable custom transformations, although vectorized Pandas operations are usually preferred when an equivalent exists.

In [39]:
students_enhanced["Performance"] = students_enhanced["Score"].apply(
    lambda x: "Excellent" if x >= 90
    else "Good" if x >= 80
    else "Needs Improvement"
)

students_enhanced[["Name", "Score", "Performance"]]

      Name  Score        Performance
0   Marwan     92          Excellent
1      Ali     85               Good
2  Mahmoud     78  Needs Improvement
3    Hager     95          Excellent

### `map()`

`map()` is convenient for element-wise replacement or transformation.

In [40]:
students_enhanced["Subteam_Upper"] = students_enhanced["Subteam"].map(str.upper)

students_enhanced[["Name", "Subteam", "Subteam_Upper"]]

      Name     Subteam Subteam_Upper
0   Marwan          AI            AI
1      Ali  Navigation    NAVIGATION
2  Mahmoud    Hardware      HARDWARE
3    Hager  Navigation    NAVIGATION

### `assign()`

`assign()` is useful when you want to create a chain of transformations without repeatedly mutating the original DataFrame.

In [41]:
students_assigned = students.assign(
    Passed=students["Score"] >= 60,
    Score_Percent=students["Score"] / 100
)

students_assigned

      Name     Subteam  Join_Date  Score  Passed  Score_Percent
0   Marwan          AI       2025     92    True           0.92
1      Ali  Navigation       2025     85    True           0.85
2  Mahmoud    Hardware       2024     78    True           0.78
3    Hager  Navigation       2025     95    True           0.95

### Removing columns

Use `drop()` to remove unwanted columns.

Prefer creating a new DataFrame when you want to keep the original unchanged.

In [42]:
without_score = students.drop(columns=["Score"])
without_score

      Name     Subteam  Join_Date
0   Marwan          AI       2025
1      Ali  Navigation       2025
2  Mahmoud    Hardware       2024
3    Hager  Navigation       2025

### `transform()`

`transform()` is especially useful with groups because it returns a result with the **same shape as the original data**.

For example, we can add the average score of each student's subteam to every corresponding row.

In [43]:
students_with_group_mean = students.copy()

students_with_group_mean["Subteam_Mean_Score"] = (
    students_with_group_mean
    .groupby("Subteam")["Score"]
    .transform("mean")
)

students_with_group_mean[["Name", "Subteam", "Score", "Subteam_Mean_Score"]]

      Name     Subteam  Score  Subteam_Mean_Score
0   Marwan          AI     92                92.0
1      Ali  Navigation     85                90.0
2  Mahmoud    Hardware     78                78.0
3    Hager  Navigation     95                90.0

## 10. Data Cleaning

Data cleaning means finding and handling problems such as:

- missing values
- duplicate rows
- incorrect data types
- inconsistent text
- invalid or extreme values

A good cleaning workflow is:

**Detect → Decide → Handle → Validate**

### Missing values

First inspect missing values:

```python
df.isna().sum()
```

Then decide whether to drop or fill them.

In [44]:
messy_students = pd.DataFrame({
    "Name": ["Ali", "Sara", "Omar", "Nour", "Nour"],
    "Age": [25, None, 22, 30, 30],
    "Score": [88, 95, None, 72, 72],
    "Subteam": ["AI", "Navigation", "AI", None, None]
})

messy_students

   Name   Age  Score     Subteam
0   Ali  25.0   88.0          AI
1  Sara   NaN   95.0  Navigation
2  Omar  22.0    NaN          AI
3  Nour  30.0   72.0        None
4  Nour  30.0   72.0        None

In [45]:
messy_students.isna().sum()

Name       0
Age        1
Score      1
Subteam    2
dtype: int64

### Dropping missing values

- `dropna()` removes rows containing missing values
- `dropna(subset=[...])` checks only selected columns
- `dropna(axis=1)` works on columns

In [46]:
messy_students.dropna(subset=["Age"])

   Name   Age  Score Subteam
0   Ali  25.0   88.0      AI
2  Omar  22.0    NaN      AI
3  Nour  30.0   72.0    None
4  Nour  30.0   72.0    None

### Filling missing values

You can fill missing values with a constant or a statistic such as the mean.

In [47]:
filled_students = messy_students.copy()

filled_students["Age"] = filled_students["Age"].fillna(
    filled_students["Age"].mean()
)

filled_students["Subteam"] = filled_students["Subteam"].fillna("Unknown")

filled_students

   Name    Age  Score     Subteam
0   Ali  25.00   88.0          AI
1  Sara  26.75   95.0  Navigation
2  Omar  22.00    NaN          AI
3  Nour  30.00   72.0     Unknown
4  Nour  30.00   72.0     Unknown

### Forward fill and interpolation

For ordered data, forward filling can carry the previous value forward.

Interpolation estimates missing numerical values between known values.

In [48]:
time_data = pd.DataFrame({
    "Day": [1, 2, 3, 4, 5],
    "Value": [10.0, None, 30.0, None, 50.0]
})

time_data["Forward_Fill"] = time_data["Value"].ffill()
time_data["Interpolated"] = time_data["Value"].interpolate()

time_data

   Day  Value  Forward_Fill  Interpolated
0    1   10.0          10.0          10.0
1    2    NaN          10.0          20.0
2    3   30.0          30.0          30.0
3    4    NaN          30.0          40.0
4    5   50.0          50.0          50.0

## 11. Duplicates

Check how many duplicate rows exist with:

```python
df.duplicated().sum()
```

Remove duplicates with:

```python
df.drop_duplicates()
```

You can also define which columns determine whether a row is duplicated.

In [49]:
print("Duplicate rows:", messy_students.duplicated().sum())

deduplicated = messy_students.drop_duplicates()
deduplicated

Duplicate rows: 1

   Name   Age  Score     Subteam
0   Ali  25.0   88.0          AI
1  Sara   NaN   95.0  Navigation
2  Omar  22.0    NaN          AI
3  Nour  30.0   72.0        None

In [50]:
messy_students.drop_duplicates(subset=["Name"], keep="first")

   Name   Age  Score     Subteam
0   Ali  25.0   88.0          AI
1  Sara   NaN   95.0  Navigation
2  Omar  22.0    NaN          AI
3  Nour  30.0   72.0        None

## 12. Data Types

Correct data types make analysis more reliable.

Common conversions:

```python
df["Age"] = df["Age"].astype(int)
df["Date"] = pd.to_datetime(df["Date"])
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")
```

`errors="coerce"` converts values that cannot be parsed into `NaN`, which can then be handled during cleaning.

In [51]:
type_data = pd.DataFrame({
    "Age": ["20", "25", "30"],
    "Score": ["88", "92", "invalid"],
    "Date": ["2025-01-10", "2025-02-15", "2025-03-20"]
})

type_data["Age"] = type_data["Age"].astype(int)
type_data["Score"] = pd.to_numeric(type_data["Score"], errors="coerce")
type_data["Date"] = pd.to_datetime(type_data["Date"])

type_data.dtypes

Age               int64
Score           float64
Date     datetime64[ns]
dtype: object

## 13. String Operations

Pandas provides a `.str` accessor for vectorized string operations.

Common operations include:

- `.str.strip()`
- `.str.lower()`
- `.str.upper()`
- `.str.title()`
- `.str.contains()`
- `.str.startswith()`
- `.str.endswith()`
- `.str.replace()`
- `.str.split()`
- `.str.extract()`

In [52]:
names = pd.Series(["  marwan", "ALI  ", " Mahmoud ", "hager"])

clean_names = (
    names
    .str.strip()
    .str.title()
)

clean_names

0     Marwan
1        Ali
2    Mahmoud
3      Hager
dtype: object

In [53]:
emails = pd.Series([
    "ali@gmail.com",
    "sara@example.com",
    "omar@gmail.com"
])

emails[emails.str.contains("@gmail.com")]

0     ali@gmail.com
2    omar@gmail.com
dtype: object

In [54]:
email_domains = emails.str.split("@").str[1]
email_domains

0      gmail.com
1    example.com
2      gmail.com
dtype: object

## 14. Outlier Detection

One common approach is the **IQR (Interquartile Range)** method.

1. Calculate Q1
2. Calculate Q3
3. `IQR = Q3 - Q1`
4. Values below `Q1 - 1.5 × IQR` or above `Q3 + 1.5 × IQR` are flagged

Outliers should not automatically be deleted. First determine whether they are errors or legitimate observations.

In [55]:
prices = pd.Series([2.0, 2.5, 3.0, 3.2, 3.5, 4.0, 4.2, 25.0])

Q1 = prices.quantile(0.25)
Q3 = prices.quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = prices[(prices < lower_bound) | (prices > upper_bound)]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Outliers:")
print(outliers)

Q1: 2.875
Q3: 4.05
IQR: 1.1749999999999998
Outliers:
7    25.0
dtype: float64

### Clipping values

If domain knowledge gives a valid range, `clip()` can constrain values to that range.

In [56]:
clipped_prices = prices.clip(lower=0.5, upper=20)
clipped_prices

0     2.0
1     2.5
2     3.0
3     3.2
4     3.5
5     4.0
6     4.2
7    20.0
dtype: float64

## 15. GroupBy and Aggregation

`groupby()` follows the **Split → Apply → Combine** idea:

1. **Split** rows into groups
2. **Apply** an aggregation or transformation
3. **Combine** the results

Common aggregations include `sum`, `mean`, `count`, `min`, and `max`.

In [57]:
students.groupby("Subteam")["Score"].mean()

Subteam
AI            92.0
Hardware      78.0
Navigation    90.0
Name: Score, dtype: float64

In [58]:
students.groupby("Subteam").agg(
    Average_Score=("Score", "mean"),
    Maximum_Score=("Score", "max"),
    Student_Count=("Name", "count")
)

            Average_Score  Maximum_Score  Student_Count
Subteam
AI                   92.0             92              1
Hardware             78.0             78              1
Navigation           90.0             95              2

### `pivot_table()`

A pivot table summarizes data across two dimensions.

In [59]:
sales = pd.DataFrame({
    "Day": ["Mon", "Mon", "Tue", "Tue", "Wed", "Wed"],
    "Type": ["Latte", "Tea", "Latte", "Tea", "Latte", "Tea"],
    "Revenue": [90, 40, 120, 55, 100, 60]
})

pd.pivot_table(
    sales,
    values="Revenue",
    index="Day",
    columns="Type",
    aggfunc="sum",
    fill_value=0
)

Type  Latte  Tea
Day
Mon      90   40
Tue     120   55
Wed     100   60

## 16. Merging DataFrames

Real datasets are often split across multiple tables.

`pd.merge()` combines DataFrames using matching keys.

Common join types:

- **inner** → only matching rows from both tables
- **left** → all rows from the left table
- **right** → all rows from the right table
- **outer** → all rows from both tables

In [60]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3],
    "Name": ["Ali", "Sara", "Omar"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [100, 150, 80, 200]
})

customers

   CustomerID  Name
0           1   Ali
1           2  Sara
2           3  Omar

In [61]:
orders

   OrderID  CustomerID  Amount
0      101           1     100
1      102           2     150
2      103           2      80
3      104           4     200

In [62]:
inner_join = pd.merge(
    orders,
    customers,
    on="CustomerID",
    how="inner"
)

inner_join

   OrderID  CustomerID  Amount  Name
0      101           1     100   Ali
1      102           2     150  Sara
2      103           2      80  Sara

In [63]:
left_join = pd.merge(
    orders,
    customers,
    on="CustomerID",
    how="left"
)

left_join

   OrderID  CustomerID  Amount  Name
0      101           1     100   Ali
1      102           2     150  Sara
2      103           2      80  Sara
3      104           4     200   NaN

### `concat()`

`concat()` is useful for stacking DataFrames vertically or horizontally.

For example, when multiple DataFrames have the same columns, vertical concatenation combines their rows.

In [64]:
part_1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Score": [88, 92]
})

part_2 = pd.DataFrame({
    "Name": ["Omar", "Nour"],
    "Score": [79, 95]
})

combined = pd.concat([part_1, part_2], ignore_index=True)
combined

   Name  Score
0   Ali     88
1  Sara     92
2  Omar     79
3  Nour     95

## 17. Practical Data-Analysis Workflow

A typical Pandas workflow looks like this:

```text
Load
  ↓
Inspect
  ↓
Clean
  ↓
Select / Filter
  ↓
Transform
  ↓
Group / Merge
  ↓
Validate
  ↓
Export
```

The important idea is that Pandas is not just about memorizing commands. The commands are tools used to move through this workflow.

## 18. Quick Reference

| Task | Common Pandas tool |
|---|---|
| First rows | `df.head()` |
| Last rows | `df.tail()` |
| Random rows | `df.sample()` |
| Structure | `df.info()` |
| Statistics | `df.describe()` |
| Dimensions | `df.shape` |
| One column | `df["col"]` |
| Label-based access | `df.loc[]` |
| Position-based access | `df.iloc[]` |
| Single cell | `df.at[]`, `df.iat[]` |
| Sort | `df.sort_values()` |
| Filter | `df[condition]` |
| List matching | `df["col"].isin(...)` |
| Range filtering | `df["col"].between(...)` |
| SQL-like filtering | `df.query(...)` |
| Conditional replacement | `where()`, `mask()` |
| Add column | `df["new"] = ...` |
| Element-wise function | `apply()`, `map()` |
| Group-aware transformation | `transform()` |
| Add/remove columns | assignment, `drop()` |
| Missing values | `isna()`, `dropna()`, `fillna()` |
| Duplicates | `duplicated()`, `drop_duplicates()` |
| Type conversion | `astype()`, `to_numeric()`, `to_datetime()` |
| String cleaning | `.str.*` |
| Group analysis | `groupby()` |
| Multiple aggregations | `agg()` |
| Pivot summary | `pivot_table()` |
| Combine tables by key | `merge()` |
| Stack tables | `concat()` |

## 19. Key Takeaways

- A **Series** is one-dimensional; a **DataFrame** is two-dimensional.
- Inspect your data before modifying it.
- Prefer `loc` for labels and `iloc` for positions.
- Use boolean conditions for flexible filtering.
- Use vectorized Pandas operations when possible.
- Treat data cleaning as a deliberate process: **detect → decide → handle → validate**.
- `groupby()` is one of the most important tools for summarizing data.
- `merge()` and `concat()` solve different table-combination problems.
- Keep the original DataFrame when possible by using `.copy()` before major transformations.